title: Nepomuk
description: >-
  Some notes about life.
baseurl: ""
url: "https://nepomuk.pajonk.me"
github_username: nepda
show_excerpts: false
author:
  name: 'Nepomuk'
  email: ''

timezone: Europe/Berlin

theme: minima

minima:
  date_format: "%-d. %b %Y"
  social_links:
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1021809/nepomuk-pajonk" }
    - { platform: github,  user_url: "https://github.com/nepda" }

header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
   - .idea/
   - Gemfile
   - Gemfile.lock
